### PR TITLE
Fix nested serializer lookup

### LINKED ISSUE #30: undefined method `load_all_lazy_relationships' for nil:NilClass
Hi there!

What a wonderful gem! Thanks for the great work and for sharing this. It really improves the database performance when removing a lot of N+1 queries. I have set everything in my controller and custom serializer but when running my specs I encounter the following error:

`undefined method `load_all_lazy_relationships' for nil:NilClass`

My custom serializer is called `MemberListSerializer` and is rendering `User` Model Class objects.

Am I missing something? Are custom serializers allowed?

### PR DESCRIPTION
**Pull request by stokarenko**
It fixes #30 

`undefined method 'load_all_lazy_relationships' for nil:NilClass` exception is raising in specific env.

Lets fix two yet different causes of this:
1) host application uses customized serializers lookup (`ActiveModelSerializers.config.serializer_lookup_chain`), so `ams_lazy_relationships` should use the same lookup in order to get the same result;
2) in case of missed serializer, `ActiveModelSerializers` will inline nested object right into `relationships` as it is, so `ams_lazy_relationships` should keep rolling as well.

### CODE REVIEW

**Comment by stokarenko** [comment]
Hey again @Bajena )

Should I do something with that codeclimate issue? `deep_load_for_yielded_records` looks pretty well for me )

**Comment by Bajena** [comment]
Great work @stokarenko! Really impressive 🎩 Thanks for your time and high quality PR (nice descriptions and specs).

Btw. if I may ask -  how did you get to know this gem and how are you using it?

**Comment by Bajena** [comment]
Unfortunately the master build has failed after merge (https://travis-ci.com/Bajena/ams_lazy_relationships/builds/142470412).
I suppose the older versions of active model serializers didn't support the serializer lookup chain feature.

If you still have some time (and patience :D) it'd be great if you took at them. If not I'll try fixing them (probably by disabling the new specs depending on the AMS version).

**Comment by stokarenko** [comment]
Hey @Bajena , nice to meet you! )

thanks a lot for your gem, it works like a charm )

> if I may ask - how did you get to know this gem and how are you using it?

well, I'm trying to solve a massive N+1 issues within a large SOA project. We realized that `active-model-serializer` will fetch `every` association defined in serializer just for maintaining so-called `relationships` data. I.e. it fires a massive N+1 even without explicit `includes`.. o_O

So I started to develop my own solution for this, fixed N+1 at least for `relationships` data, started to think how to preload the things for explicit `includes` as well, came to `laziness` idea, then asked google is there is something like this - bingo )

> If you still have some time (and patience :D) it'd be great if you took at them.

definitively I will do that on 6th Jun, right after vacation )

also I would like a push one more PR here, it will be a kind of `dig` but for nested associations, like 

```ruby
class SomeSerializer

  def some_attr
    lazy_dig(:organization, :logo)&.url
  end
end
```

it is already implemented, just need to tune a code a bit and write specs ) That is the last thing which turns your gem into a graceful rescue for my project )

**Comment by Bajena** [comment]
> thanks a lot for your gem, it works like a charm )

Great to hear it. I had a very similar motivation for building it - we have a big API with lots of controllers loading nested data. It'd be really hard to specify proper Rails-style `includes`  for all of them and maintain it. Also `bullet` gem wasn't very useful in our case.

> definitively I will do that on 6th Jun, right after vacation )

🙇 

> also I would like a push one more PR here, it will be a kind of dig but for nested associations, like

Yeah, great idea. I already had a few cases when I needed to specify a lazy relationship only for fetching one attribute. Looking forward to seeing it!

**Comment by Bajena** [comment]
Btw @stokarenko you seem to be a very proficient developer. I'd be honored to grant you a maintainer privilege if you'd like. Would you be interested in that?

**Comment by stokarenko** [comment]
@Bajena

>> If you still have some time (and patience :D) it'd be great if you took at them.

> definitively I will do that on 6th Jun, right after vacation )

Here we go! ) https://github.com/Bajena/ams_lazy_relationships/pull/43

`lazy_dig` is coming as well )

> I'd be honored to grant you a maintainer privilege if you'd like. Would you be interested in that?

Sure thing, thank you! Lets do the great things together )

**Comment by Bajena** [comment]
> Sure thing, thank you! Lets do the great things together )

Great! I've sent you an invitation to collaborate 🎉
